classDiagram

Pessoa <|-- Professor
Pessoa <|-- Estudante
Professor <|-- Coordenador
Turma "0..1" o-- "1" Professor : agregação
Turma "0..1" *-- "1..40" Estudante : composição

%% Comentário: Uma turma é considerada viável se tiver pelo menos 20 estudantes matriculados.
  %% Essa lógica será implementada no método verificarViabilidade() da classe Turma.
  %% Gwen
