classDiagram

Pessoa <|-- Professor
Pessoa <|-- Estudante
Professor <|-- Coordenador
Turma "1" o-- "1..1" Professor : catedrático/adjunto
Turma "0..1" o-- "0..1" Professor : assistente
Turma "0..1" *-- "1..40" Estudante

%% Comentário: Uma turma é considerada viável se tiver pelo menos 20 estudantes matriculados.
  %% Essa lógica será implementada no método verificarViabilidade() da classe Turma.

%% Documentos do Estudante
IDocumento <|.. Boletim
IDocumento <|.. Diploma

%% Documentos Institucionais
IDocumento <|.. Circular


