classDiagram

Pessoa <|-- Professor
Pessoa <|-- Estudante
Professor <|-- Coordenador
Turma "0..1" o-- "1" Professor : agregação
Turma "0..1" *-- "1..40" Estudante : composição

%% Comentário: Uma turma é considerada viável se tiver pelo menos 20 estudantes matriculados.
  %% Essa lógica será implementada no método verificarViabilidade() da classe Turma.

%% Documentos do Estudante
IDocumento <|.. Boletim
IDocumento <|.. Diploma

%% Documentos Institucionais
IDocumento <|.. Circular


    class Turma {
        -nome : string
        -professor : IProfessor*
        -alunos : vector~IEstudante*~
        -maxAlunos : size_t
        +Turma(nome : string, professor : IProfessor*, maxAlunos : int)
        +adicionarAluno(aluno : IEstudante*) : bool
        +emitirRelatorioNotas() : void
	+verificarViabilidade() : bool
    }
